package io.jbock.simple.processor;

import io.jbock.testing.compile.Compilation;
import org.junit.jupiter.api.Test;

import javax.tools.JavaFileObject;

import static io.jbock.simple.processor.Compilers.simpleCompiler;
import static io.jbock.testing.compile.CompilationSubject.assertThat;
import static io.jbock.testing.compile.JavaFileObjects.forSourceLines;

class BuilderTest {

    @Test
    void noParameters() {
        JavaFileObject component = forSourceLines("test.TestClass",
                "package test;",
                "",
                "import io.jbock.simple.Component;",
                "import io.jbock.simple.Inject;",
                "",
                "final class TestClass {",
                "  static class A {",
                "    @Inject A() {}",
                "  }",
                "",
                "  @Component(mockBuilder = true)",
                "  interface AComponent {",
                "    A getA();",
                "",
                "    @Component.Builder",
                "    interface Builder {",
                "      AComponent build();",
                "    }",
                "  }",
                "}");

        Compilation compilation = simpleCompiler().compile(component);
        assertThat(compilation).succeeded();
        assertThat(compilation).generatedSourceFile("test.TestClass_AComponent_Impl")
                .containsLines(
                        "package test;",
                        "",
                        "final class TestClass_AComponent_Impl implements TestClass.AComponent {",
                        "  private final TestClass.A a;",
                        "",
                        "  private TestClass_AComponent_Impl(TestClass.A a) {",
                        "    this.a = a;",
                        "  }",
                        "",
                        "  @Override",
                        "  public TestClass.A getA() {",
                        "    return a;",
                        "  }",
                        "",
                        "  static Builder_Impl builder() {",
                        "    return new Builder_Impl();",
                        "  }",
                        "",
                        "  public static final class Builder_Impl implements TestClass.AComponent.Builder {",
                        "    @Override",
                        "    public TestClass.AComponent build() {",
                        "      TestClass.A a = new TestClass.A();",
                        "      return new TestClass_AComponent_Impl(a);",
                        "    }",
                        "  }",
                        "}");
    }

    @Test
    void builderParameterIdentity() {
        JavaFileObject component = forSourceLines("test.TestClass",
                "package test;",
                "",
                "import io.jbock.simple.Component;",
                "import io.jbock.simple.Inject;",
                "",
                "final class TestClass {",
                "",
                "  @Component(mockBuilder = true)",
                "  public interface AComponent {",
                "    String getS();",
                "",
                "    @Component.Builder",
                "    interface Builder {",
                "      Builder withS(String s);",
                "      AComponent build();",
                "    }",
                "  }",
                "}");
        Compilation compilation = simpleCompiler().compile(component);
        assertThat(compilation).succeeded();
        assertThat(compilation).generatedSourceFile("test.TestClass_AComponent_Impl")
                .containsLines(
                        "package test;",
                        "",
                        "public final class TestClass_AComponent_Impl implements TestClass.AComponent {",
                        "  private final String s;",
                        "",
                        "  private TestClass_AComponent_Impl(String s) {",
                        "    this.s = s;",
                        "  }",
                        "",
                        "  @Override",
                        "  public String getS() {",
                        "    return s;",
                        "  }",
                        "",
                        "  public static Builder_Impl builder() {",
                        "    return new Builder_Impl();",
                        "  }",
                        "",
                        "  public static final class Builder_Impl implements TestClass.AComponent.Builder {",
                        "    String s;",
                        "",
                        "    @Override",
                        "    public Builder_Impl withS(String s) {",
                        "      this.s = s;",
                        "      return this;",
                        "    }",
                        "",
                        "    @Override",
                        "    public TestClass.AComponent build() {",
                        "      return new TestClass_AComponent_Impl(s);",
                        "    }",
                        "  }",
                        "}");
    }

    @Test
    void builderParameter() {
        JavaFileObject component = forSourceLines("test.TestClass",
                "package test;",
                "",
                "import io.jbock.simple.Component;",
                "import io.jbock.simple.Inject;",
                "import io.jbock.simple.Named;",
                "",
                "final class TestClass {",
                "  static class A {",
                "    @Inject A(@Named(\"a\") String s) {}",
                "  }",
                "",
                "  static class B {",
                "    @Inject B(A a) {}",
                "  }",
                "",
                "  @Component(mockBuilder = true, publicMockBuilder = true)",
                "  public interface AComponent {",
                "    B getB();",
                "",
                "    @Component.Builder",
                "    interface Builder {",
                "      Builder withS(@Named(\"a\") String s);",
                "      AComponent build();",
                "    }",
                "  }",
                "}");
        Compilation compilation = simpleCompiler().compile(component);
        assertThat(compilation).succeeded();
        assertThat(compilation).generatedSourceFile("test.TestClass_AComponent_Impl")
                .containsLines(
                        "package test;",
                        "",
                        "public final class TestClass_AComponent_Impl implements TestClass.AComponent {",
                        "  private final TestClass.B b;",
                        "",
                        "  private TestClass_AComponent_Impl(TestClass.B b) {",
                        "    this.b = b;",
                        "  }",
                        "",
                        "  @Override",
                        "  public TestClass.B getB() {",
                        "    return b;",
                        "  }",
                        "",
                        "  public static Builder_Impl builder() {",
                        "    return new Builder_Impl();",
                        "  }",
                        "",
                        "  public static final class Builder_Impl implements TestClass.AComponent.Builder {",
                        "    String s;",
                        "",
                        "    @Override",
                        "    public Builder_Impl withS(String s) {",
                        "      this.s = s;",
                        "      return this;",
                        "    }",
                        "",
                        "    public MockBuilder withMocks() {",
                        "      return new MockBuilder(this.s);",
                        "    }",
                        "",
                        "    @Override",
                        "    public TestClass.AComponent build() {",
                        "      TestClass.A a = new TestClass.A(this.s);",
                        "      TestClass.B b = new TestClass.B(a);",
                        "      return new TestClass_AComponent_Impl(b);",
                        "    }",
                        "  }",
                        "",
                        "  public static final class MockBuilder {",
                        "    private final String s;",
                        "    private TestClass.A a;",
                        "    private TestClass.B b;",
                        "",
                        "    private MockBuilder(String s) {",
                        "      this.s = s;",
                        "    }",
                        "",
                        "    public TestClass.AComponent build() {",
                        "      TestClass.A a = this.a != null ? this.a : new TestClass.A(this.s);",
                        "      TestClass.B b = this.b != null ? this.b : new TestClass.B(a);",
                        "      return new TestClass_AComponent_Impl(b);",
                        "    }",
                        "",
                        "    public MockBuilder a(TestClass.A a) {",
                        "      this.a = a;",
                        "      return this;",
                        "    }",
                        "",
                        "    public MockBuilder b(TestClass.B b) {",
                        "      this.b = b;",
                        "      return this;",
                        "    }",
                        "  }",
                        "}");
    }
}